# Generated by Django 4.2.19 on 2025-03-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spendings', '0004_spending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
