# Generated by Django 4.2.19 on 2025-03-17 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_spendings', '0006_spending_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='spending',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_spendings.spending'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
