# Generated by Django 4.2.19 on 2025-03-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spendings', '0007_picture_spending_alter_spending_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='sum_currency',
            field=models.IntegerField(default=0),
        ),
    ]
