# Generated by Django 4.2.19 on 2025-03-20 11:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sections', '0004_alter_section_sum_currency_alter_section_sum_uah_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_spendings', '0008_spending_sum_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='spending',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_spendings.spending'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spending',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sections.section'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='sum_currency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='spending',
            name='sum_uah',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='spending',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
