# Generated by Django 4.2.19 on 2025-04-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spendings', '0011_alter_picture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
