# Generated by Django 4.2.19 on 2025-03-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('sum_uah', models.IntegerField(default=0)),
                ('sum_currency', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
