# Generated by Django 4.2.19 on 2025-03-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
        migrations.AddField(
            model_name='section',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
